### ISSUE TITLE
response path from user application to extension

### ISSUE THREAD

**Issue by h9jiang** [YaronKoller/envoy#18]
_Description:_ 
Currently, we are using stream_demuxer and convert filter to accomplish retrieving message from pubsub topics and deliver to user application. There are currently no support to let user application to acknowledge specific messages. The process can be described below.
```
pubsub   ->   demuxer   ->   reverse bridge   ->   convert filter   ->   router   ->   user application
```

What we are trying to build is a new response path from user application to extension and finally acknowledge those request that user application acknowledged. 

Rules need to follow by user application: 
user application can choose response or not when he receive cloud event information, but only when user application return an HTTP request with a status code OK, the filter will take this as a valid acknowledge. Otherwise, it will take as not acknowledged by user application. 

#### Gcp Convert Filter Design

Design ideas: 
Gcp convert filter is now a decoder filter which will only be called when there is data flow from down stream to upstream. However, in order to let the filter take over the job, the filter will transform to be a stream filter that deal with both way of stream transfer. 

I will explain in detail about what's the new functionality of it by introducing the whole process of the work flow. 
1. Decode Data function will be triggered when there is unary gRPC request from extension to user application, the body contains a Received Message proto format and ack id is one of its field. 
2. During the Decode Data function, the convert filter will store the ack id string as a member variable. Since the convert filter is now a stream filter, it will not be destructed when the user application send back the response. 
3. Encode Data function will be triggered when there is a HTTP response from user application to envoy. If and only if the HTTP request is a Ok status, the filter will wrap the ack id string previous stored to be a proto message, serialized it to be a proto format string and replace the HTTP request body with it. 
4. The proto string will then arrive at the reverse bridge filter, the reverse bridge filter will put back the frame it previous stripped and make it a gRPC unary call response. 
5. Extension will receive a unary call response and the reply contains the ack id string. Extension will use that string to reply back to pubsub to finally confirm that acknowledgement. 

```
pubsub   ->   demuxer   ->   reverse bridge   ->   convert filter   ->   router   ->   user application
                                                          v                                 |
                                                        ack_id                              |                                    
                                                          v                       ok        |               
pubsub   <-   demuxer   <-   reverse bridge   <-   convert filter   <-   router   <----------
```

**Comment by YaronKoller** [comment]
We forgot to link the PR to this issue before merging, but I think this was already fully implemented!
